---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pull-secret
  namespace: va-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-pull-secret
    type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .url }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: url
      remoteRef:
        key: platform/registry
        property: url
    - secretKey: username
      remoteRef:
        key: platform/registry
        property: username
    - secretKey: password
      remoteRef:
        key: platform/registry
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pull-secret
  namespace: va-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-pull-secret
    type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .url }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: url
      remoteRef:
        key: platform/registry
        property: url
    - secretKey: username
      remoteRef:
        key: platform/registry
        property: username
    - secretKey: password
      remoteRef:
        key: platform/registry
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pull-secret
  namespace: va-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-pull-secret
    type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .url }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: url
      remoteRef:
        key: platform/registry
        property: url
    - secretKey: username
      remoteRef:
        key: platform/registry
        property: username
    - secretKey: password
      remoteRef:
        key: platform/registry
        property: password
