grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.k8s.va.atmodev.net
    tls:
      - secretName: grafana-tls
        hosts: [grafana.k8s.va.atmodev.net]
  persistence:
    enabled: false   # дашборды в ConfigMaps через sidecar, PVC не нужен
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 30d
    retentionSize: "50GB"
    nodeSelector:
      node-pool: storage
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-retain
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-pool: storage
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-retain
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 5Gi

kubeEtcd:
  enabled: true
  endpoints:
    - 176.113.118.177
    - 176.113.118.178
    - 176.113.118.179

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
