apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.4.1
    helm:
      values: |
        # Контроллеры ESO должны работать на воркерах.
        nodeSelector:
          storage.enabled: "true"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        webhook:
          nodeSelector:
            storage.enabled: "true"

        certController:
          nodeSelector:
            storage.enabled: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

