apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 84.5.0
      helm:
        releaseName: obs-metrics
        valueFiles:
          - $values/platform/argocd-apps/observability/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/ovsal/k8s-va.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
