---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://github.com/ovsal/k8s-va.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.0
      helm:
        valueFiles:
          - $values/platform/apps/secrets/eso-values.yaml
    - repoURL: https://github.com/ovsal/k8s-va.git
      targetRevision: main
      path: platform/apps/secrets
      directory:
        include: 'cluster-secret-store.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
