all:
  hosts:
    cp-1:
      ansible_host: 176.113.118.177      # ЗАМЕНИТЬ
      ansible_user: ansible
    cp-2:
      ansible_host: 176.113.118.178      # ЗАМЕНИТЬ
      ansible_user: ansible
    cp-3:
      ansible_host: 176.113.118.179      # ЗАМЕНИТЬ
      ansible_user: ansible
    worker-1:
      ansible_host: 176.113.118.180      # ЗАМЕНИТЬ
      ansible_user: ansible
    worker-2:
      ansible_host: 176.113.118.181      # ЗАМЕНИТЬ
      ansible_user: ansible
  children:
    kube_control_plane:
      hosts:
        cp-1:
        cp-2:
        cp-3:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        cp-1:
        cp-2:
        cp-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
