---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure applications
  sourceRepos:
    - https://github.com/ovsal/k8s-va.git
    - https://charts.external-secrets.io
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    - https://helm.releases.hashicorp.com
    - https://vmware-tanzu.github.io/helm-charts
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
# Далее: каждое дочернее Application будет в своей директории.
# Argo CD подхватит их через path: platform/apps
# и будет рекурсивно синкать.
