---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://github.com/ovsal/k8s-va.git
      targetRevision: main
      ref: values
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 7.1.4
      helm:
        valueFiles:
          - $values/platform/apps/backup/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
