apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    template:
      data:
        # velero expects an AWS credentials file format under key "cloud"
        cloud: |
          [default]
          aws_access_key_id={{ .access_key }}
          aws_secret_access_key={{ .secret_key }}
  data:
    - secretKey: access_key
      remoteRef:
        key: platform/velero
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: platform/velero
        property: secret_key
